### ISSUE TITLE
Error after signing in

### ISSUE THREAD

**Issue by Danielx64** [sylveon/discord-ban-appeals#13]
I don't know if I am doing anything wrong here but after signing in to discord, I get the message

`{"errorType":"Error","errorMessage":"Failed to get user access token","trace":["Error: Failed to get user access token","    at Runtime.exports.handler (/var/task/src/func/oauth-callback.js:27:19)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}`

This is on a fresh install with no changes being made to source code. Where should I start to troubleshoot this? Does the GitHub repo need to have the same name as the parent repo?

**Comment by sylveon** [comment]
Did you set the client ID and client secret correctly?

**Comment by sylveon** [comment]
Closing for inactivity. Please reopen if you still have any issues.
