### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NoodlesDev987** [sylveon/discord-ban-appeals#20]
When I click authorize it redirects me back and then I receive:
```
{"errorType":"Error","errorMessage":"Failed to get user access token","trace":["Error: Failed to get user access token","    at Runtime.exports.handler (/var/task/src/func/oauth-callback.js:30:19)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}
```

**Comment by NoodlesDev987** [comment]
This was Discord api issue
