### ISSUE TITLE
Submit appeal form error message

### ISSUE THREAD

**Issue by OviiiOne** [sylveon/discord-ban-appeals#35]
Hi, out of the blue users are unable to submit appeals on my server.

I have forked this repo and just translated some things to have it in Spanish, last week it was working just fine.

Now whenever they try to send the form (after logging in) they receive this message:

`{"errorType":"SyntaxError","errorMessage":"Unexpected token ] in JSON at position 44","trace":["SyntaxError: Unexpected token ] in JSON at position 44","    at JSON.parse (<anonymous>)","    at Runtime.exports.handler (/var/task/func/submit-appeal.js:37:35)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}`

I tried to check if there was an error in the code, but I can't find the file submit-appeal.js and I don't know what to do.

**Comment by sylveon** [comment]
Am I right in assuming you're using Netlify forms? Does the issue happens if you stop using those and instead use a webhook?

**Comment by OviiiOne** [comment]
I don't know how to do that >_<
