### ISSUE TITLE
Error: This Function has Crashed

### ISSUE THREAD

**Issue by Exie610** [sylveon/discord-ban-appeals#73]
Users currently get this error when submitting a ban appeal: 

This function has crashed
An unhandled error in the function code triggered the following message:

Error - Failed to submit message

Stack trace
Error: Failed to submit message
    at Runtime.handler (/var/task/func/submit-appeal.js:14976:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Connection details
Netlify internal ID: 01H32RQM2FCPN0X04FP8DZF46Q

![image](https://github.com/sylveon/discord-ban-appeals/assets/76196350/b1f4b7e4-a15f-46aa-8d42-dd74be81b7cb)

**Comment by sylveon** [comment]
Seems like something is broken with the webhook. Check the console log of the function from your netlify dashboard - the full error returned by discord is here.
